# EDA Triatlón: recopilación y limpieza de datos

Este notebook documenta el proceso para pasar de los CSV originales descargados desde las APIs a un único dataset final limpio y comparable: `data/triatlon_clean.csv`.

El objetivo de esta fase no es analizar todavía las hipótesis, sino preparar una tabla común para poder comparar resultados profesionales de distancia Ironman y distancia olímpica.

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
import sys

# Rutas robustas: funcionan si ejecutas desde la raiz, codigo o notebook.
BASE_DIR = Path.cwd()
if BASE_DIR.name in ["codigo", "notebook"]:
    PROJECT_DIR = BASE_DIR.parent
else:
    PROJECT_DIR = BASE_DIR

if str(PROJECT_DIR) not in sys.path:
    sys.path.append(str(PROJECT_DIR))

from codigo.visualizacion import preparar_df_graficos

# Rutas principales del proyecto
DATA_DIR = PROJECT_DIR / "data"
IRONMAN_DIR = DATA_DIR / "ironman_2015_2025"
OLIMPICA_DIR = DATA_DIR / "olimpica_2016_2025"

IRONMAN_PRO_PATH = IRONMAN_DIR / "ironman_wc_2015_2025_pro_results.csv"
OLIMPICA_ALL_PATH = OLIMPICA_DIR / "olimpica_2016_2025_all_results.csv"
TRIATLON_CLEAN_PATH = DATA_DIR / "triatlon_clean.csv"

## 1. Concatenación de resultados 
### 1.1 Ironman

En esta sección se importan los CSV de Ironman World Championship Kona por año y género. Después se unen en un único DataFrame llamado `all_results`.

No aparece el año 2020 porque no hay un resultado equivalente del campeonato mundial de Kona para ese año.

In [3]:
men_2015 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2015_male_results.csv")
women_2015 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2015_female_results.csv")

men_2016 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2016_male_results.csv")
women_2016 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2016_female_results.csv")

men_2017 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2017_male_results.csv")
women_2017 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2017_female_results.csv")

men_2018 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2018_male_results.csv")
women_2018 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2018_female_results.csv")

men_2019 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2019_male_results.csv")
women_2019 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2019_female_results.csv")

men_2021 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2021_male_results.csv")
women_2021 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2021_female_results.csv")

men_2022 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2022_male_results.csv")
women_2022 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2022_female_results.csv")

men_2023 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2023_male_results.csv")
women_2023 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2023_female_results.csv")

men_2024 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2024_male_results.csv")
women_2024 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2024_female_results.csv")

men_2025 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2025_male_results.csv")
women_2025 = pd.read_csv(IRONMAN_DIR / "ironman_wc_2025_female_results.csv")

all_results = pd.concat([men_2015,women_2015,men_2016,women_2016,men_2017,women_2017,men_2018,women_2018,men_2019,women_2019,men_2021,women_2021,
    men_2022, women_2022, men_2023, women_2023, men_2024, women_2024, men_2025, women_2025], ignore_index=True)

all_results.to_csv(IRONMAN_DIR / "ironman_wc_2015_2025_all_results.csv", index=False)

all_results.info()

<class 'pandas.DataFrame'>
RangeIndex: 31497 entries, 0 to 31496
Data columns (total 50 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   championship_year            31497 non-null  int64
 1   event_name                   31497 non-null  str
 2   event_id                     31497 non-null  str
 3   source_url                   31497 non-null  str
 4   source_api_url               31497 non-null  str
 5   athlete                      31497 non-null  str
 6   first_name                   31497 non-null  str
 7   last_name                    31497 non-null  str
 8   bib                          31497 non-null  int64
 9   bib_display                  109 non-null    object
 10  country_iso2                 31457 non-null  str
 11  country_iso3                 31459 non-null  str
 12  country                      31497 non-null  str
 13  gender                       31497 non-null  str
 14  age_group                    31497 non-null  str
 15  finisher                     31497 non-null  bool
 16  dnf                          31497 non-null  bool
 17  dns                          31497 non-null  bool
 18  dq                           31497 non-null  bool
 19  finish_time                  28159 non-null  str
 20  finish_seconds               31497 non-null  int64
 21  swim_time                    29650 non-null  str
 22  swim_seconds                 31497 non-null  int64
 23  t1_time                      15127 non-null  object
 24  t1_seconds                   31497 non-null  int64
 25  bike_time                    29005 non-null  str
 26  bike_seconds                 31497 non-null  int64
 27  t2_time                      15127 non-null  object
 28  t2_seconds                   31497 non-null  int64
 29  run_time                     28158 non-null  str
 30  run_seconds                  31497 non-null  int64
 31  finish_rank_overall          31497 non-null  int64
 32  finish_rank_gender           31497 non-null  int64
 33  finish_rank_group            31497 non-null  int64
 34  swim_rank_overall            31497 non-null  int64
 35  swim_rank_gender             31497 non-null  int64
 36  swim_rank_group              31497 non-null  int64
 37  bike_rank_overall            31497 non-null  int64
 38  bike_rank_gender             31497 non-null  int64
 39  bike_rank_group              31497 non-null  int64
 40  run_rank_overall             31497 non-null  int64
 41  run_rank_gender              31497 non-null  int64
 42  run_rank_group               31497 non-null  int64
 43  total_distance_completed_km  31220 non-null  float64
 44  swim_distance_completed_km   31220 non-null  float64
 45  bike_distance_completed_km   31220 non-null  float64
 46  run_distance_completed_km    31220 non-null  float64
 47  result_id                    31497 non-null  str
 48  created_on                   31497 non-null  str
 49  modified_on                  31497 non-null  str
dtypes: bool(4), float64(4), int64(20), object(3), str(19)
memory usage: 11.2+ MB

#### Filtrado de profesionales Ironman

El dataset original de Ironman contiene tanto profesionales como grupos de edad. Para que la comparación con la distancia olímpica sea coherente, se conservan únicamente atletas profesionales:

- `MPRO`: hombres profesionales.
- `FPRO`: mujeres profesionales.

El resultado se guarda como `ironman_wc_2015_2025_pro_results.csv`.

In [4]:
all_results_pro = all_results[all_results["age_group"].isin(["MPRO", "FPRO"])]

print(all_results_pro.info())

all_results_pro.to_csv(IRONMAN_DIR / "ironman_wc_2015_2025_pro_results.csv", index=False)

<class 'pandas.DataFrame'>
Index: 954 entries, 0 to 31495
Data columns (total 50 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   championship_year            954 non-null    int64
 1   event_name                   954 non-null    str
 2   event_id                     954 non-null    str
 3   source_url                   954 non-null    str
 4   source_api_url               954 non-null    str
 5   athlete                      954 non-null    str
 6   first_name                   954 non-null    str
 7   last_name                    954 non-null    str
 8   bib                          954 non-null    int64
 9   bib_display                  109 non-null    object
 10  country_iso2                 954 non-null    str
 11  country_iso3                 954 non-null    str
 12  country                      954 non-null    str
 13  gender                       954 non-null    str
 14  age_group                    954 non-null    str
 15  finisher                     954 non-null    bool
 16  dnf                          954 non-null    bool
 17  dns                          954 non-null    bool
 18  dq                           954 non-null    bool
 19  finish_time                  727 non-null    str
 20  finish_seconds               954 non-null    int64
 21  swim_time                    868 non-null    str
 22  swim_seconds                 954 non-null    int64
 23  t1_time                      362 non-null    object
 24  t1_seconds                   954 non-null    int64
 25  bike_time                    806 non-null    str
 26  bike_seconds                 954 non-null    int64
 27  t2_time                      362 non-null    object
 28  t2_seconds                   954 non-null    int64
 29  run_time                     727 non-null    str
 30  run_seconds                  954 non-null    int64
 31  finish_rank_overall          954 non-null    int64
 32  finish_rank_gender           954 non-null    int64
 33  finish_rank_group            954 non-null    int64
 34  swim_rank_overall            954 non-null    int64
 35  swim_rank_gender             954 non-null    int64
 36  swim_rank_group              954 non-null    int64
 37  bike_rank_overall            954 non-null    int64
 38  bike_rank_gender             954 non-null    int64
 39  bike_rank_group              954 non-null    int64
 40  run_rank_overall             954 non-null    int64
 41  run_rank_gender              954 non-null    int64
 42  run_rank_group               954 non-null    int64
 43  total_distance_completed_km  904 non-null    float64
 44  swim_distance_completed_km   904 non-null    float64
 45  bike_distance_completed_km   904 non-null    float64
 46  run_distance_completed_km    904 non-null    float64
 47  result_id                    954 non-null    str
 48  created_on                   954 non-null    str
 49  modified_on                  954 non-null    str
dtypes: bool(4), float64(4), int64(20), object(3), str(19)
memory usage: 354.0+ KB
None

### 1.2 Olímpica

En esta sección se importan los CSV de Juegos Olímpicos y finales de World Triathlon Championship Series. Todos corresponden a pruebas élite de distancia olímpica.

Los CSV se cargan por evento y género, y después se unen en `olimpica_all_results`. Este archivo funciona como dataset combinado de la modalidad olímpica antes de la homogeneización final.

In [5]:
olympic_games_2016_female = pd.read_csv(OLIMPICA_DIR / "olympic_games_2016_female_results.csv")
olympic_games_2016_male = pd.read_csv(OLIMPICA_DIR / "olympic_games_2016_male_results.csv")

olympic_games_2020_female = pd.read_csv(OLIMPICA_DIR / "olympic_games_2020_female_results.csv")
olympic_games_2020_male = pd.read_csv(OLIMPICA_DIR / "olympic_games_2020_male_results.csv")

olympic_games_2024_female = pd.read_csv(OLIMPICA_DIR / "olympic_games_2024_female_results.csv")
olympic_games_2024_male = pd.read_csv(OLIMPICA_DIR / "olympic_games_2024_male_results.csv")


wtcs_final_2016_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2016_female_results.csv")
wtcs_final_2016_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2016_male_results.csv")

wtcs_final_2017_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2017_female_results.csv")
wtcs_final_2017_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2017_male_results.csv")

wtcs_final_2018_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2018_female_results.csv")
wtcs_final_2018_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2018_male_results.csv")

wtcs_final_2019_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2019_female_results.csv")
wtcs_final_2019_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2019_male_results.csv")

wtcs_final_2021_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2021_female_results.csv")
wtcs_final_2021_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2021_male_results.csv")

wtcs_final_2022_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2022_female_results.csv")
wtcs_final_2022_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2022_male_results.csv")

wtcs_final_2023_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2023_female_results.csv")
wtcs_final_2023_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2023_male_results.csv")

wtcs_final_2024_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2024_female_results.csv")
wtcs_final_2024_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2024_male_results.csv")

wtcs_final_2025_female = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2025_female_results.csv")
wtcs_final_2025_male = pd.read_csv(OLIMPICA_DIR / "wtcs_final_2025_male_results.csv")


olimpica_all_results = pd.concat([olympic_games_2016_female, olympic_games_2016_male, olympic_games_2020_female, olympic_games_2020_male,
    olympic_games_2024_female, olympic_games_2024_male, wtcs_final_2016_female, wtcs_final_2016_male, wtcs_final_2017_female,
    wtcs_final_2017_male, wtcs_final_2018_female, wtcs_final_2018_male, wtcs_final_2019_female, wtcs_final_2019_male, wtcs_final_2021_female,
    wtcs_final_2021_male, wtcs_final_2022_female, wtcs_final_2022_male, wtcs_final_2023_female, wtcs_final_2023_male, wtcs_final_2024_female,
    wtcs_final_2024_male, wtcs_final_2025_female, wtcs_final_2025_male], ignore_index=True)

olimpica_all_results.head()

,dataset,championship_year,event_id,event_title,event_slug,event_country,program_id,program_name,program_date,gender,...,total_time,start_num,result_id,source_url,source_api_url,swim,t1,bike,t2,run
0,olympic_games,2016,100636,Rio de Janeiro 2016 Olympic Games,2016-rio-de-janeiro-olympic-games,Brazil,305291,Elite Women,2016-08-20,female,...,01:56:16,20,544636,https://events.triathlon.org/2016-rio-de-janei...,https://events.triathlon.org/api/results/10063...,00:19:12,00:00:56,01:01:21,00:00:38,00:34:09
1,olympic_games,2016,100636,Rio de Janeiro 2016 Olympic Games,2016-rio-de-janeiro-olympic-games,Brazil,305291,Elite Women,2016-08-20,female,...,01:56:56,18,544637,https://events.triathlon.org/2016-rio-de-janei...,https://events.triathlon.org/api/results/10063...,00:19:12,00:00:54,01:01:22,00:00:38,00:34:50
2,olympic_games,2016,100636,Rio de Janeiro 2016 Olympic Games,2016-rio-de-janeiro-olympic-games,Brazil,305291,Elite Women,2016-08-20,female,...,01:57:01,14,544638,https://events.triathlon.org/2016-rio-de-janei...,https://events.triathlon.org/api/results/10063...,00:19:09,00:00:54,01:01:26,00:00:38,00:34:54
3,olympic_games,2016,100636,Rio de Janeiro 2016 Olympic Games,2016-rio-de-janeiro-olympic-games,Brazil,305291,Elite Women,2016-08-20,female,...,01:57:04,16,544639,https://events.triathlon.org/2016-rio-de-janei...,https://events.triathlon.org/api/results/10063...,00:19:10,00:00:53,01:01:25,00:00:41,00:34:55
4,olympic_games,2016,100636,Rio de Janeiro 2016 Olympic Games,2016-rio-de-janeiro-olympic-games,Brazil,305291,Elite Women,2016-08-20,female,...,01:57:29,32,544640,https://events.triathlon.org/2016-rio-de-janei...,https://events.triathlon.org/api/results/10063...,00:19:13,00:00:52,01:01:24,00:00:39,00:35:21

In [6]:
print(olimpica_all_results.shape)

olimpica_all_results.to_csv(OLIMPICA_DIR / "olimpica_2016_2025_all_results.csv", index=False)

(1338, 29)

## 4. Limpieza y homogeneización de ambas modalidades

A partir de este punto se trabaja con dos datasets combinados:

- `ironman_wc_2015_2025_pro_results.csv`.
- `olimpica_2016_2025_all_results.csv`.

El objetivo es filtrar resultados válidos, convertir tiempos a segundos y crear columnas comunes para poder unir ambas modalidades.

### 4.1 Carga de CSVs combinados

Se cargan los dos archivos principales que servirán como base para construir el dataset final.

In [7]:
ironman = pd.read_csv(IRONMAN_PRO_PATH)
olimpica = pd.read_csv(OLIMPICA_ALL_PATH)

### 4.2 Filtrado de resultados válidos

Se eliminan resultados no comparables, como abandonos, descalificaciones o atletas sin tiempo final válido.

In [8]:
# Ironman:
ironman = ironman[
    (ironman["finisher"] == True) &
    (ironman["dnf"] == False) &
    (ironman["dns"] == False) &
    (ironman["dq"] == False)].copy()


# Olímpica:
olimpica["position"] = pd.to_numeric(olimpica["position"], errors="coerce")
olimpica = olimpica.dropna(subset=["position", "total_time"]).copy()

### 4.3 Conversión de tiempos a segundos

Para comparar segmentos y calcular porcentajes es necesario transformar los tiempos en formato texto (`hh:mm:ss` o `mm:ss`) a segundos numéricos.

In [9]:
def time_to_seconds(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip()

    if x in ["", "nan", "None", "DNF", "DNS", "DSQ", "LAP"]:
        return np.nan

    parts = x.split(":")

    try:
        parts = [int(float(p)) for p in parts]
    except ValueError:
        return np.nan

    if len(parts) == 3:
        h, m, s = parts
        return h * 3600 + m * 60 + s

    if len(parts) == 2:
        m, s = parts
        return m * 60 + s

    return np.nan

### 4.4 Homogeneización de columnas

Ironman y World Triathlon usan nombres de columnas distintos. En esta sección se renombran las variables para que ambas modalidades compartan la misma estructura.

In [10]:
# IRONMAN
ironman_clean = ironman[[
    "championship_year", "event_name", "athlete", "country_iso3", "gender",
    "finish_rank_group", "finish_time", "finish_seconds",
    "swim_time", "swim_seconds", "t1_time", "t1_seconds",
    "bike_time", "bike_seconds", "t2_time", "t2_seconds",
    "run_time", "run_seconds"
]].copy()

ironman_clean["tipo_distancia"] = "ironman"

ironman_clean = ironman_clean.rename(columns={
    "championship_year": "año",
    "event_name": "evento",
    "athlete": "atleta",
    "country_iso3": "pais",
    "gender": "genero",
    "finish_rank_group": "posicion",
    "finish_time": "tiempo_total",
    "finish_seconds": "segundos_total",
    "swim_time": "tiempo_natacion",
    "swim_seconds": "segundos_natacion",
    "t1_time": "tiempo_t1",
    "t1_seconds": "segundos_t1",
    "bike_time": "tiempo_bicicleta",
    "bike_seconds": "segundos_bicicleta",
    "t2_time": "tiempo_t2",
    "t2_seconds": "segundos_t2",
    "run_time": "tiempo_carrera",
    "run_seconds": "segundos_carrera"
})


# OlÍMPICA

olimpica_clean = olimpica[[
    "championship_year", "event_title", "athlete_full_name", "athlete_noc",
    "gender", "position", "total_time", "swim", "t1", "bike", "t2", "run", "dataset"
]].copy()

olimpica_clean["tipo_distancia"] = "olimpica"

olimpica_clean = olimpica_clean.rename(columns={
    "championship_year": "año",
    "event_title": "evento",
    "athlete_full_name": "atleta",
    "athlete_noc": "pais",
    "gender": "genero",
    "position": "posicion",
    "total_time": "tiempo_total",
    "swim": "tiempo_natacion",
    "t1": "tiempo_t1",
    "bike": "tiempo_bicicleta",
    "t2": "tiempo_t2",
    "run": "tiempo_carrera",
    "dataset": "tipo_evento"
})

for col in ["tiempo_total", "tiempo_natacion", "tiempo_t1", "tiempo_bicicleta", "tiempo_t2", "tiempo_carrera"]:
    nueva_col = col.replace("tiempo_", "segundos_")
    olimpica_clean[nueva_col] = olimpica_clean[col].apply(time_to_seconds)

## 5. Creación del dataset final

Se seleccionan las columnas comunes, se concatenan ambas modalidades y se aplica el mismo criterio competitivo: primeras 40 posiciones por carrera y género.

Además, la función `preparar_df_graficos` elimina tiempos no reales, normaliza género y crea las variables necesarias para las hipótesis, como porcentajes por segmento y `top_10`.

In [11]:
columnas_comunes = [
    "tipo_distancia", "año", "evento", "atleta", "pais", "genero", "posicion",
    "tiempo_total", "segundos_total",
    "tiempo_natacion", "segundos_natacion",
    "tiempo_t1", "segundos_t1",
    "tiempo_bicicleta", "segundos_bicicleta",
    "tiempo_t2", "segundos_t2",
    "tiempo_carrera", "segundos_carrera"
]

triatlon_clean = pd.concat([
    ironman_clean[columnas_comunes],
    olimpica_clean[columnas_comunes]
], ignore_index=True)


# Para comparar ambas modalidades con el mismo criterio competitivo, se limita el análisis a las primeras 40 posiciones de cada carrera/genero.
posicion_maxima = 40
triatlon_clean = preparar_df_graficos(triatlon_clean, posicion_max=posicion_maxima)
triatlon_clean.to_csv(TRIATLON_CLEAN_PATH, index=False)

print("Dataset final:", triatlon_clean.shape)
print("Archivo creado:", TRIATLON_CLEAN_PATH)
triatlon_clean.head()

Dataset final: (1634, 24)
Archivo creado: c:\Users\ander\OneDrive\Desktop\Bootcamp\EDA_triatlon\EDA_Triatlon_Ander\data\triatlon_clean.csv

,tipo_distancia,año,evento,atleta,pais,genero,posicion,tiempo_total,segundos_total,tiempo_natacion,...,segundos_bicicleta,tiempo_t2,segundos_t2,tiempo_carrera,segundos_carrera,pct_natacion,pct_bicicleta,pct_carrera,pct_transiciones,top_10
0,ironman,2015,2015 IRONMAN World Championship,Jan Frodeno,DEU,Male,1.0,8:14:40,29680,0:50:50,...,16047,NaN,131,2:52:21,10341,10.276280,54.066712,34.841644,0.815364,True
1,ironman,2015,2015 IRONMAN World Championship,Andreas Raelert,DEU,Male,2.0,8:17:43,29863,0:52:24,...,16252,NaN,149,2:50:02,10202,10.528078,54.421860,34.162676,0.887386,True
2,ironman,2015,2015 IRONMAN World Championship,Timothy O'Donnell,USA,Male,3.0,8:18:50,29930,0:52:24,...,15973,NaN,146,2:55:46,10546,10.504511,53.367858,35.235550,0.892082,True
3,ironman,2015,2015 IRONMAN World Championship,Andy Potts,USA,Male,4.0,8:21:25,30085,0:50:56,...,16361,NaN,140,2:53:45,10425,10.157886,54.382583,34.651820,0.807711,True
4,ironman,2015,2015 IRONMAN World Championship,Tyler Butterfield,BMU,Male,5.0,8:23:09,30189,0:52:33,...,16175,NaN,161,2:56:19,10579,10.444202,53.579118,35.042565,0.934115,True