In [2]:
import pandas as pd

# Ironman Distance Data

In [3]:
men_2015 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2015_men_results.csv")
women_2015 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2015_women_results.csv")

men_2016 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2016_men_results.csv")
women_2016 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2016_women_results.csv")

men_2017 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2017_men_results.csv")
women_2017 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2017_women_results.csv")

men_2018 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2018_men_results.csv")
women_2018 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2018_women_results.csv")

men_2019 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2019_men_results.csv")
women_2019 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2019_women_results.csv")

men_2021 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2021_men_results.csv")
women_2021 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2021_women_results.csv")

men_2022 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2022_men_results.csv")
women_2022 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2022_women_results.csv")

men_2023 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2023_men_results.csv")
women_2023 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2023_women_results.csv")

men_2024 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2024_men_results.csv")
women_2024 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2024_women_results.csv")

men_2025 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2025_men_results.csv")
women_2025 = pd.read_csv("./Data/ironman_2015_2025/ironman_wc_2025_women_results.csv")

all_results = pd.concat([men_2015,women_2015,men_2016,women_2016,men_2017,women_2017,men_2018,women_2018,men_2019,women_2019,men_2021,women_2021,
    men_2022, women_2022, men_2023, women_2023, men_2024, women_2024, men_2025, women_2025], ignore_index=True)

all_results.to_csv("./Data/ironman_2015_2025/ironman_wc_2015_2025_all_results.csv",index=False)

all_results.head()

,championship_year,event_date,event_date_iso,event_id,event_name,event_label,external_event_name,source_url,source_api_url,tracker_year,...,run_rank_overall,run_rank_gender,run_rank_group,total_distance_completed_km,swim_distance_completed_km,bike_distance_completed_km,run_distance_completed_km,result_id,created_on,modified_on
0,2015,10/10/2015,2015-10-10T00:00:00Z,d57bb0ac-432e-4d3e-a4ba-7ad7439b8b02,2015 IRONMAN World Championship,2015 IRONMAN World Championship,NaN,https://labs-v2.competitor.com/results/event/e...,https://labs-v2.competitor.com/api/results?wtc...,2015,...,1,1,1,226.0,3.8,180.0,42.2,3331bd82-3023-45c6-874d-09b60c4ff4aa,2015-10-13T01:20:38Z,2025-04-20T14:35:17Z
1,2015,10/10/2015,2015-10-10T00:00:00Z,d57bb0ac-432e-4d3e-a4ba-7ad7439b8b02,2015 IRONMAN World Championship,2015 IRONMAN World Championship,NaN,https://labs-v2.competitor.com/results/event/e...,https://labs-v2.competitor.com/api/results?wtc...,2015,...,2,2,2,226.0,3.8,180.0,42.2,e524b300-f463-406c-8e15-d802737dd5fa,2015-10-13T01:21:59Z,2025-04-20T14:34:32Z
2,2015,10/10/2015,2015-10-10T00:00:00Z,d57bb0ac-432e-4d3e-a4ba-7ad7439b8b02,2015 IRONMAN World Championship,2015 IRONMAN World Championship,NaN,https://labs-v2.competitor.com/results/event/e...,https://labs-v2.competitor.com/api/results?wtc...,2015,...,3,3,3,226.0,3.8,180.0,42.2,a6e59d43-6103-400f-9d7d-8ba890169e1d,2015-10-13T01:20:52Z,2025-04-20T14:35:10Z
3,2015,10/10/2015,2015-10-10T00:00:00Z,d57bb0ac-432e-4d3e-a4ba-7ad7439b8b02,2015 IRONMAN World Championship,2015 IRONMAN World Championship,NaN,https://labs-v2.competitor.com/results/event/e...,https://labs-v2.competitor.com/api/results?wtc...,2015,...,4,4,4,226.0,3.8,180.0,42.2,50a1d68d-ec7d-426f-adec-a14bafdd179c,2015-10-13T01:22:28Z,2025-04-20T14:33:46Z
4,2015,10/10/2015,2015-10-10T00:00:00Z,d57bb0ac-432e-4d3e-a4ba-7ad7439b8b02,2015 IRONMAN World Championship,2015 IRONMAN World Championship,NaN,https://labs-v2.competitor.com/results/event/e...,https://labs-v2.competitor.com/api/results?wtc...,2015,...,5,5,5,226.0,3.8,180.0,42.2,03dcef82-7fc4-453c-98a6-cf93ac9571f1,2015-10-13T01:21:51Z,2025-04-20T14:33:37Z

In [4]:
all_results_pro = all_results[all_results["age_group"].isin(["MPRO", "FPRO"])]

print(all_results_pro.shape)

all_results_pro.to_csv("./Data/ironman_2015_2025/ironman_wc_2015_2025_pro_results.csv",index=False)

(954, 55)

# Olimpic Distance Data

In [5]:
olympic_games_2016_female = pd.read_csv("./Data/olimpica_2016_2025/olympic_games_2016_female_results.csv")
olympic_games_2016_male = pd.read_csv("./Data/olimpica_2016_2025/olympic_games_2016_male_results.csv")

olympic_games_2020_female = pd.read_csv("./Data/olimpica_2016_2025/olympic_games_2020_female_results.csv")
olympic_games_2020_male = pd.read_csv("./Data/olimpica_2016_2025/olympic_games_2020_male_results.csv")

olympic_games_2024_female = pd.read_csv("./Data/olimpica_2016_2025/olympic_games_2024_female_results.csv")
olympic_games_2024_male = pd.read_csv("./Data/olimpica_2016_2025/olympic_games_2024_male_results.csv")


wtcs_final_2016_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2016_female_results.csv")
wtcs_final_2016_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2016_male_results.csv")

wtcs_final_2017_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2017_female_results.csv")
wtcs_final_2017_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2017_male_results.csv")

wtcs_final_2018_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2018_female_results.csv")
wtcs_final_2018_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2018_male_results.csv")

wtcs_final_2019_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2019_female_results.csv")
wtcs_final_2019_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2019_male_results.csv")

wtcs_final_2021_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2021_female_results.csv")
wtcs_final_2021_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2021_male_results.csv")

wtcs_final_2022_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2022_female_results.csv")
wtcs_final_2022_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2022_male_results.csv")

wtcs_final_2023_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2023_female_results.csv")
wtcs_final_2023_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2023_male_results.csv")

wtcs_final_2024_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2024_female_results.csv")
wtcs_final_2024_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2024_male_results.csv")

wtcs_final_2025_female = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2025_female_results.csv")
wtcs_final_2025_male = pd.read_csv("./Data/olimpica_2016_2025/wtcs_final_2025_male_results.csv")


olimpica_all_results = pd.concat([olympic_games_2016_female, olympic_games_2016_male, olympic_games_2020_female, olympic_games_2020_male,
    olympic_games_2024_female, olympic_games_2024_male, wtcs_final_2016_female, wtcs_final_2016_male, wtcs_final_2017_female,
    wtcs_final_2017_male, wtcs_final_2018_female, wtcs_final_2018_male, wtcs_final_2019_female, wtcs_final_2019_male, wtcs_final_2021_female,
    wtcs_final_2021_male, wtcs_final_2022_female, wtcs_final_2022_male, wtcs_final_2023_female, wtcs_final_2023_male, wtcs_final_2024_female,
    wtcs_final_2024_male, wtcs_final_2025_female, wtcs_final_2025_male], ignore_index=True)

olimpica_all_results.head()

,air_temperature,athlete_age,athlete_country_name,athlete_first,athlete_full_name,athlete_id,athlete_last,athlete_noc,athlete_yob,bike,...,total_time,water_temperature,weather,wetsuit,bike_distance_m,bike_laps,run_distance_m,run_laps,swim_distance_m,swim_laps
0,NaN,40,United States,Gwen,Gwen Jorgensen,40887,Jorgensen,USA,1986,01:01:21,...,01:56:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,44,Switzerland,Nicola,Nicola Spirig,5372,Spirig,SUI,1982,01:01:22,...,01:56:56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,40,Great Britain,Vicky,Vicky Holland,7795,Holland,GBR,1986,01:01:26,...,01:57:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,37,Great Britain,Non,Non Stanford,31438,Stanford,GBR,1989,01:01:25,...,01:57:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,38,Chile,Barbara,Barbara Riveros,6150,Riveros,CHI,1987,01:01:24,...,01:57:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(olimpica_all_results.shape)

olimpica_all_results.to_csv("./Data/olimpica_2016_2025/olimpica_2016_2025_all_results.csv",index=False)

(1338, 45)

### Clean Datasets

In [12]:
#IRONMAN
ironman_clean = all_results_pro[[ "championship_year","event_name", "athlete", "country_iso3", "gender", "finish_rank_overall", "finish_rank_gender",
    "finish_time", "finish_seconds", "swim_time", "swim_seconds", "t1_time", "t1_seconds", "bike_time", "bike_seconds", "t2_time",
    "t2_seconds", "run_time", "run_seconds", "age_group"]].copy()

ironman_clean["tipo_de_distancia"] = "ironman"

ironman_clean = all_results_pro.rename(columns={
    "championship_year": "año",
    "event_name": "evento",
    "athlete": "nombre_atleta",
    "country_iso3": "pais",
    "gender": "genero",
    "finish_rank_overall": "posicion_general",
    "finish_rank_gender": "posicion_genero",
    "finish_time": "tiempo_total",
    "finish_seconds": "segundos_totales",
    "swim_time": "tiempo_natacion",
    "swim_seconds": "segundos_natacion",
    "t1_time": "tiempo_t1",
    "t1_seconds": "segundos_t1",
    "bike_time": "tiempo_bicicleta",
    "bike_seconds": "segundos_bicicleta",
    "t2_time": "tiempo_t2",
    "t2_seconds": "segundos_t2",
    "run_time": "tiempo_carrera",
    "run_seconds": "segundos_carrera",
    "age_group": "grupo_edad"})

#OLIMPICA
olimpica_clean = olimpica_all_results[["championship_year", "event_title", "athlete_full_name", "athlete_noc", "gender", "position", "total_time", "swim", "t1",
    "bike", "t2", "run", "dataset"]].copy()

olimpica_clean["tipo_de_distancia"] = "olimpica"

olimpica_clean = olimpica_clean.rename(columns={
    "championship_year": "año",
    "event_title": "evento",
    "athlete_full_name": "nombre_atleta",
    "athlete_noc": "pais",
    "gender": "genero",
    "position": "posicion_general",
    "total_time": "tiempo_total",
    "swim": "tiempo_natacion",
    "t1": "tiempo_t1",
    "bike": "tiempo_bicicleta",
    "t2": "tiempo_t2",
    "run": "tiempo_carrera",
    "dataset": "tipo_de_evento" })

In [ ]:
# Dado que la olimpica viene separado por genero, hay que añadir que posicion_genero == posicion general, para mantener misma estructura que Ironman.

olimpica_clean["posicion_genero"] = olimpica_clean["posicion_general"]

### Convertir tiempos en segundos para homogeneizar tiempos entre distancias

In [11]:
def time_to_seconds(time_value):
    if pd.isna(time_value):
        return None

    parts = str(time_value).split(":")
    parts = [int(float(part)) for part in parts]

    if len(parts) == 3:
        hours, minutes, seconds = parts
        return hours * 3600 + minutes * 60 + seconds

    if len(parts) == 2:
        minutes, seconds = parts
        return minutes * 60 + seconds

    return None


for col in ["tiempo_total", "tiempo_natacion", "t1", "tiempo_bici", "t2", "tiempo_correr"]:
    olimpica_clean[col.replace("_time", "_seconds") if col.endswith("_time") else col + "_seconds"] = olimpica_clean[col].apply(time_to_seconds)

KeyError: 'tiempo_total'